name: Docker Image CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: docker/login-action@v2
      - name: docker login
        env:
          DOCKER_USER: ${{ secrets.DOCKER_USER }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: docker login -u $DOCKER_USER -p DOCKER_PASSWORD
      - name: build the docker image
        run: docker build . --file Dockerfile --tag supritshah1289-ui-test/react-test:$(date +%s)
      - name: Docker Push
        run: docker push ${{secrets.DOCKER_USER}}/docker-ui-test
